# Repository settings using probot/settings app
# You need to install: https://github.com/apps/settings
# Reference: https://github.com/probot/settings

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  # The name of the repository. Changing this will rename the repository
  name: devden
  description: The secret lair where all development magic happens
  # A URL with more information about the repository
  homepage: https://github.com/yourusername/devden
  # A comma-separated list of topics to set on the repository
  topics: devcontainer, development, configuration
  # Either `true` to make the repository private, or `false` to make it public.
  private: false
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true
  # Either `true` to enable projects for this repository, or `false` to disable them.
  has_projects: true
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true
  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true
  # Updates the default branch for this repository.
  default_branch: main
  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true
  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false
  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false
  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true 