services:
  tgnotes-service-1.1.2:
    image: tgnotes-image-1.1.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vscode
    # ports to see the web result
    #ports:
    #  - "8080:8080"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # code and config volumes mount
    volumes:
      - ..:/workspace/tgnotes:cached
      - tgnotes-node_modules:/workspace/tgnotes/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  tgnotes-node_modules:
    name: "tgnotes-node_modules-volume"