services:
  devden-service-0.0.4:
    image: devden-image-0.0.4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vscode
        USER_UID: 1000
        USER_GID: 1000
        VARIANT: "debian-12"
        # Python configuration with miniconda
        INSTALL_PYTHON: "true"
        VERSION_PYTHON: "3.12"
        # Node.js configuration with nvm
        INSTALL_NODE: "true"
        NODE_VERSION: "22"
        # Bun configuration
        INSTALL_BUN: "true"
        VERSION_BUN: "1.0.35"
        # Deno configuration
        INSTALL_DENO: "true"
        VERSION_DENO: "1.40.5"
        # Docker configuration
        INSTALL_DOCKER: "true"
        # Java/Kotlin configuration with sdkman
        INSTALL_JAVA: "true"
        JAVA_VERSION: "23"
        INSTALL_KOTLIN: "true"
        VERSION_KOTLIN: "1.9.22"
        # Go configuration with gvm
        INSTALL_GO: "true"
        VERSION_GO: "1.20.4"
        # Rust configuration with rsvm
        INSTALL_RUST: "true"
        VERSION_RUST: "1.76.0"
        # Oh My Zsh configuration
        INSTALL_OHMYZSH: "true"
        # Kubernetes tools configuration
        INSTALL_KUBECTL: "true"
        VERSION_KUBECTL: "v1.29.0"
        INSTALL_MINIKUBE: "true"
        VERSION_MINIKUBE: "v1.32.0"
        # Homebrew configuration
        INSTALL_HOMEBREW: "true"
    # ports to see the web result
    #ports:
    #  - "8080:8080"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # code and config volumes mount
    volumes:
      - ..:/workspace/devden:cached
      - devden-node_modules:/workspace/devden/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Pass environment variables to container
      NVM_DIR: /usr/local/share/nvm
      PYTHON_ROOT: /usr/local/python
      SDKMAN_DIR: /usr/local/sdkman
      GVM_DIR: /usr/local/gvm
      RSVM_DIR: /usr/local/rsvm
      BUN_INSTALL: /usr/local/share/bun
      PATH: ${PATH}:/usr/local/share/nvm/versions/node/v22/bin:/usr/local/python/bin:/usr/local/share/bun/bin:/usr/local/bin/deno:/home/linuxbrew/.linuxbrew/bin

volumes:
  devden-node_modules:
    name: "devden-node_modules-volume"
