services:
  devden-service-0.0.1:
    image: devden-image-0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vscode
    # ports to see the web result
    #ports:
    #  - "8080:8080"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # code and config volumes mount
    volumes:
      - ..:/workspace/devden:cached
      - devden-node_modules:/workspace/devden/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  devden-node_modules:
    name: "devden-node_modules-volume"
