name: Auto Assign PR Author

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to Author
        uses: technote-space/assign-author@v1
